name: Build, test, and benchmark on ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      config:
        operating-system: [ubuntu-latest]
        llvm-version: [10]
    runs-on: ${{ config.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh ${{ config.llvm-version }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run benchmarks
      run: cargo bench
